image: gcc:9

stages:
  - build_stage
  - test_stage

build:
  stage: build_stage
  script:
    - make
  artifacts:
    paths:
      - extra
    expire_in: 30 mins

test:
  stage: test_stage
  allow_failure: true
  script:
    - apt-get update && apt install --no-install-recommends -y libtap-formatter-junit-perl bats man time
    - make
    - ./mybats check.bats
  artifacts:
    when: always
    reports:
      junit:
        - "*.tap.xml"

test-priv:
  stage: test_stage
  allow_failure: true
  script:
    - apt-get update && apt install --no-install-recommends -y libtap-formatter-junit-perl bats man time
    - make
    - ./mybats priv.bats
  artifacts:
    when: always
    reports:
      junit:
        - "*.tap.xml"

test-local:
  stage: test_stage
  script:
    - apt-get update && apt install --no-install-recommends -y libtap-formatter-junit-perl bats man time
    - make
    - ./mybats local.bats
  artifacts:
    when: always
    reports:
      junit:
        - "*.tap.xml"
